### ISSUE TITLE
Locally good, but not working on S3

### ISSUE THREAD

**Issue by rmaddox** [wavexx/fgallery#34]
I have it locally working well, but not on the S3:
http://www.startyourowngoldmine.com/images/syogm/tanzanians/

Someone knows why?

**Comment by wavexx** [comment]
On 09/12/15 18:27, Rosario Maddox wrote:
> I have it locally working well, but not on the S3:
> http://www.startyourowngoldmine.com/images/syogm/tanzanians/

If you look at the console you see:

The stylesheet
http://www.startyourowngoldmine.com/images/syogm/tanzanians/index.css
was not loaded because its MIME type, "text/plain", is not "text/css".

Looks like you have to fix the mime type served by S3, but since I never
used S3 I cannot help you there.

**Comment by rmaddox** [comment]
Alright thanks, I got it now! That's it. Yes.
