### ISSUE TITLE
Allow to run fgallery in "update" mode

### ISSUE THREAD

**Issue by wavexx** [wavexx/fgallery#37]
Allow to run `fgallery -u` to update an existing gallery, only performing the 1st pass on the directory, updating only newer or modified files along the way.

**Comment by johndescs** [comment]
I completely second this, especially for writing/fixing captions after generating a first rough gallery. Would be even better if it could detect someway that the output is already the same gallery but just older… not sure if this would be easy though.

**Comment by wavexx** [comment]
Indeed, that's exactly how I felt the need for it. We can reload our own data.json to know exactly what's already in the gallery, and do an mtime based check to see if the image needs re-processing.

**Comment by Tristor** [comment]
Is there any traction on this?  My Perl is a bit rusty, but I might be willing to take a crack at this at some point in the near future if you don't have time to do so currently.  This would be great for me because I just started using the software and my beginning gallery size has over 500 images.  Processing takes quite awhile, but all operations after I get going are additive, so it doesn't make sense for the software to reprocess the whole gallery every time for 1 or 2 photos being added.

**Comment by wavexx** [comment]
There's some rework to do in the way the scanning is done to support this.

We'd need to keep track of original path names and mtimes, which are now discarded.

I also don't want to add any "private" info into the public json file, so it needs to be saved elsewhere with an additional option (something like ``--state file``, which when provided will keep updating the galleries).

All in all, nothing massive, but not something I'm adding soon. At the moment I'm working on a hw project which is sucking most of my time.

**Comment by mossyoak1101** [comment]
Any progress on this? This would be a fantastic feature as I am constantly adding photos to my galleries.

**Comment by kensanata** [comment]
A solution that doesn't store the original path names and thus only works when no file name sanitisation happened is in PR https://github.com/wavexx/fgallery/pull/85
