### ISSUE TITLE
An alternative method to deal with exif fails 

### ISSUE THREAD

**Issue by NeutralKaon** [wavexx/fgallery#57]
I've recently been experimenting with making an HDR image from a stack of images obtained a Raspberry Pi camera, and using fgallery to host a timeseries of the last _n_ of them somewhere on a webserver. This works great, but HDR-ification (correctly) nukes the exif metadata of the resulting stack. 

As a consequence, I've noticed that line ~599-612 of fgallery deals with missing timestamps by setting them to that of the previous image or the unix epoch. 

I'd personally prefer defaulting to the file modification date, and hence have just slightly modified line [599](https://github.com/wavexx/fgallery/blob/master/fgallery#L599) to silently fail back to that by

`my $idate = $props->{'DateTimeOriginal'} || $props->{'DateTime'} || $props->{'FileModifyDate'} || "";
`

You may or may not think this is a good idea -- if you do, I'm happy to "turn it into software" by either adding a command line switch and/or warning statement and submit a pull request.

**Comment by wavexx** [comment]
Yes, this was mostly done as a cheat, as several cameras also nuke the EXIF data when HDR or more frequently panorama is set as a shooting mode. Since they still make sequential files, we just take the old and push it forward.

I'd edge to avoid using modtime, mostly because the tools around PTP/MTP are generally quite crappy and tend not to preserve the original value. But I've seen android for instance using a form of timestamp instead.

If the filename looks as a timestamp, and there's no EXIF info, maybe it would make sense to take it from there instead. So you could write the filenames with the time info and avoid adding a new flag.

Opinions?

**Comment by NeutralKaon** [comment]
Parsing filenames is certainly a good idea -- if not date-based they also usually are sequential, and tend to be fairly predictable (e.g. DCIM mandates something like ABCD0000.jpg). I guess one could silently sort based, in order (of failures), on exif DateTime, filename, and then perhaps modtime/last+1/epoch. I'll try and write something when I get a moment.
