### ISSUE TITLE
remove date label 

### ISSUE THREAD

**Issue by xhudik** [wavexx/fgallery#79]
i started to use fgallery - lovely program!!!

One feature I dont like is showing a date label for each photo. Is there any option/hint how to get rid of these dates? (I know it disappear when you do not mouse for some time, but still I'd like to get rid of it)

I tried `-c none` but it didnt work as I have expected ...

**Comment by wavexx** [comment]
The header is due an overhaul in order to show exif data in a sensible manner, and/or be hidden as the captions currently can (see #17). I'd like to do this without affecting the image controls (download/zoom/captions) though, which probably need to be moved elsewhere.

You cannot currently remove it by any flag, but you could kill it with some css in index.css:

  #header > span:last-child { display: none }

in either the template (to make it permanent) or the gallery (to make it local).

**Comment by xhudik** [comment]
thanks for the suggestion! 

Unfortunately, I'm not into CSS. Can you pls elaborate more on `span:last-child? `. I tried to set it in find it in `index.css`  but no luck...

**Comment by kensanata** [comment]
I think what @wavexx meant is that you can simply _add_ the line he posted to the CSS file. To translate what it does:

Inside the element with id "header", find the last span element and make it is not displayed.

Here's an example:
```html
<div id="header" style="display: block; opacity: 0.327679; visibility: visible;"><a title="Download album" href="files/album.zip"><img src="download.png"></a><span><b>Date</b>: 2016-01-09 11:19</span></div></div>
```

As you can see, that should make sure that the entire Date label does not get displayed.
