### ISSUE TITLE
Crash when large number of files are processed

### ISSUE THREAD

**Issue by rdorsch** [wavexx/fgallery#83]
Hi,

many thanks for developing and sharing fgallery, it is a really useful tool with a beautiful output :-)

I just found that fgallery crashes, when a large number of files are processed. Not sure about the detailed error, but I could image that the command line became too long. I am wondering if there is a way to specify a directory instead of each file individually. As a workaround I try to disable the zip creation using the -d option.

Here is an example (truncated, in total there are ~2.500 photographs in the 8132 directory):

```
fgallery -i -j 2 -r 8132 ~/public_html/fdbaut/photos.new
reading completed
processing 29%: IMG_20161026_085348.jpg
processing completed
generating archive...


System ERROR:
E_FAIL
error: command "7za -tzip -mmt=2 a -- /home/rd/public_html/fdbaut/photos.new/files/album.zip /home/rd/public_html/fdbaut/photos.new/files/IMG_20170311_200105.jpg /home/rd/public_html/fdbaut/photos.new/files/IMG_20170311_175535.jpg /home/rd/public_html/fdbaut/photos.new/files/IMG_20170311_125833.jpg /home/rd/public_html/fdbaut/photos.new/files/IMG_20170311_125830.jpg /home/rd/public_html/fdbaut/photos.new/files/IMG_20170311_124353.jpg /home/rd/public_html/fdbaut/photos.new/files/IMG_20170311_123112.jpg /home/rd/public_html/fdbaut/photos.new/files/IMG_20170311_121530.jpg /home/rd/public_html/fdbaut/photos.new/files/IMG_20170311_121528.jpg /home/rd/public_html/fdbaut/photos.new/files/IMG_20170311_121518.jpg ...
```

**Comment by rdorsch** [comment]
I am running 
rd@scw:~/8132$ fgallery --version
fgallery 1.8.2
rd@scw:~/8132$

**Comment by wavexx** [comment]
On Sun, Jul 23 2017, rdorsch wrote:
> I just found that fgallery crashes, when a large number of files are
> processed. Not sure about the detailed error, but I could image that
> the command line became too long.

You're probably right on the reason.

> I am wondering if there is a way to specify a directory instead of
> each file individually. As a workaround I try to disable the zip
> creation using the -d option.

fgallery passes the final processed file list to zip/7za, so that only
the files that end up in the gallery are there. The most common reason
is to skip raw/dmg doubles, sidecar files, etc.

The best way is to simply pass the input file list via stdin, both zip
and 7za support arguments to do that.

I'll have a look at this.

**Comment by kensanata** [comment]
You could replace the code in [line 808](https://github.com/wavexx/fgallery/blob/master/fgallery#L808).

Old:

```perl
    sys('7za', '-tzip', @mt, 'a', '--', "$out/$fdownload", @files);
```

New:

```perl
    my $n = 200;
    for my $i (0 .. @files/$n) {
      my $m = $n;
      $m = @files % $n if $i >= int(@files/$n);
      last unless $m;
      my @g = @files[$i*$n .. $i*$n + $m - 1];
      sys('7za', '-tzip', $mt, 'a', '--', $zipfile, @g);
    }
```

This will only fix the adding of too many files to the album if and only if you are using `7za`.

**Comment by kensanata** [comment]
For *sitelen mute* it seems that I lost the code that tries to strip the pathnames... I should investigate this in any case. I ended up with calling the archiver in batches because `man 7za` didn't have any matches for `stdin` when I looked through it, and because this would work for any archiver, zip or 7za. But perhaps -i@listfile is the right solution.
